import Clap.Keyless
import Clap.Test.KeylessFixture

/-!
# End-to-end tests for `Keyless.keyless`

Each `example` here feeds a `KeylessInput` derived from `KeylessTestFixture`
into the top-level `keyless` circuit and asserts accept (`some ()`) or reject
(`none`). Scenarios mirror the Rust prover-service test suite at
`doc/keyless-zk-proofs/prover-service/src/tests/prover_handler.rs`.

## Mapping to Rust prover-service tests

| Rust test | Lean coverage |
|-----------|---------------|
| `prove_default_request` | `Happy.input` (uses canonical Aptos JWT) |
| `prove_request_with_email` | `WithEmail.input` (alternate JWT generated by `scripts/gen_input.py`, signed with the same canonical `test_rsa_privkey.pem`) |
| `prove_request_with_no_extra_field` | `Happy.input` (its `useExtraField` is already 0) |
| `prove_request_with_aud_recovery` | `AudOverride.input` |
| `prove_request_with_sub` | `Happy.input` (its `uid_key` is already `sub`) |
| `prove_request_with_sub_no_email_verified` | `Happy.input` (its JWT has no `email_verified`) |
| `prove_request_sub_is_required_in_jwt` | NOT APPLICABLE — service-level check, not enforced by the ZK circuit. |
| `prove_request_with_wrong_uid_key` | `bad uid name` negative test |
| `prove_request_with_invalid_epk_exp_date` | `bad expDate` negative test (`expDate ≥ iat + expHorizon` fails the timestamp check) |
| `prove_request_with_future_jwt_iat` | NOT APPLICABLE — service-level wall-clock check; the circuit only enforces `expDate < iat + expHorizon`, which is independent of "now". |
| `prove_request_with_future_jwt_iat_check_disabled` | NOT APPLICABLE — same as above; no circuit-level check exists. |
| `prove_request_with_expired_jwt` | NOT APPLICABLE — the circuit does not check the JWT `exp` field (it uses `expDate`/`expHorizon` from `commit`). |
| `request_jwt_exp_field_does_not_matter` | Implicitly true — circuit ignores JWT `exp`. |
| `request_with_incorrect_nonce` | `bad epkBlinder` negative test (mismatched Poseidon nonce commitment) |
| `prove_request_all_sub_lengths` | Marked `#[ignore]` in Rust; same here. |
| (Lean-only) `SkipAudChecks` | aud-bypass / IDC-migration path not directly named in Rust tests. |
| (Lean-only) `bad signature` | RSA-2048 verification rejects |
| (Lean-only) `bad publicInputsHash` | Final Poseidon-14 equality rejects |

WARNING: each end-to-end `native_decide` runs SHA-256 over 1536 bytes,
RSA-2048 PKCS#1 v1.5 verify (≈ 65 537 modular squarings), Poseidon hashes,
base64 decode, and JSON structural checks. Compile time is ~30–120 s per
test; the full file builds in ~10 min.
-/

namespace TestKeyless
open Clap.Lang Core Primes ZMod Keyless KeylessTestFixture
open HashToField FString FArray Clap.RSA

-- ---------------------------------------------------------------------------
-- Per-stage tests on the canonical Google JWT fixture (Happy)
-- These run sub-circuits in isolation; cheaper to compile than the full
-- pipeline and useful for bisecting if a regression appears.
-- ---------------------------------------------------------------------------

/-- Length consistency: `jwt.len = header.len + payload.len`. -/
example : Happy.input.jwtRaw.b64u_jwt_no_sig_sha2_padded.len = 724 := by native_decide
example : Happy.input.jwtRaw.b64u_jwt_header_w_dot.len = 60 := by native_decide
example : Happy.input.jwtRaw.b64u_jwt_payload_sha2_padded.len = 664 := by native_decide

/-- The dot character (ASCII 46) sits at `header_w_dot.len - 1` (= byte 59). -/
example : (do
    let dot ← selectArrayValue Happy.input.jwtRaw.b64u_jwt_no_sig_sha2_padded.data
              (Happy.input.jwtRaw.b64u_jwt_header_w_dot.len - 1)
    F.assert_eq dot 46) = some () := by native_decide

/-- SHA-256 verified digest accepts the canonical padded JWT. -/
example : (Clap.Sha2.Keyless.sha256VerifiedDigest
    Happy.input.jwtRaw.b64u_jwt_no_sig_sha2_padded
    (Happy.input.jwtRaw.b64u_jwt_header_w_dot.len + Happy.input.jwtRaw.b64u_jwt_payload_sha2_padded.len)
    Happy.input.jwtRaw.sha2_num_blocks
    Happy.input.jwtRaw.sha2_num_bits
    Happy.input.jwtRaw.sha2_padding).isSome = true := by native_decide

/-- The `b64u_jwt_payload` is a prefix of `b64u_jwt_payload_sha2_padded` (substring check). -/
example : (do
    let h ← hashBytesToField Happy.input.jwtRaw.b64u_jwt_payload_sha2_padded
    assertIsSubstringFS (by decide) Happy.input.jwtRaw.b64u_jwt_payload_sha2_padded h
      Happy.input.jwtRaw.b64u_jwt_payload 0) = some () := by native_decide

/-- Base64url decoding of the unsigned payload succeeds. -/
example : (do
    let _payload : FString bn254 MAX_JWT_PAYLOAD_LEN ←
      Base64Len.base64UrlDecode (by decide) Happy.input.jwtRaw.b64u_jwt_payload
    let _ ← Base64Len.base64UrlDecodedLength 20 Happy.input.jwtRaw.b64u_jwt_payload.len
    pure ()).isSome = true := by native_decide

-- ---------------------------------------------------------------------------
-- End-to-end positive scenarios
-- ---------------------------------------------------------------------------

/-- `prove_default_request` / `prove_request_with_sub` /
    `prove_request_with_no_extra_field` / `prove_request_with_sub_no_email_verified`:
    canonical Aptos test JWT (issuer `https://accounts.google.com`),
    `uid_key = "sub"`, no `email`/`email_verified` field, `useExtraField = 0`. -/
example : keyless Happy.input = some () := by native_decide

/-- `prove_request_with_aud_recovery`: same JWT, but the verifier-facing aud
    is presented through the override path (`useAudOverride = 1`,
    `overrideAudValue = JWT-aud`). -/
example : keyless AudOverride.input = some () := by native_decide

/-- IDC-migration / aud-skip path: `skipAudChecks = 1` zeroes out the IDC's
    aud contribution and bypasses every aud-related constraint
    (no direct Rust analog). -/
example : keyless SkipAudChecks.input = some () := by native_decide

/-- `prove_request_with_email`: a Google-style JWT containing both `email` and
    `email_verified` fields, with `uid_key = "email"`. The fixture is
    generated by `scripts/gen_input.py with_email`, which signs an
    `email`-bearing JWT with the same canonical `test_rsa_privkey.pem` the
    upstream `circuit/tools/input_gen.py` uses, then runs through our
    `scripts/input_json_to_lean.py` converter. The shared ephemeral-key
    triple keeps the nonce commitment compatible. -/
example : keyless WithEmail.input = some () := by native_decide

-- ---------------------------------------------------------------------------
-- Negative tests: mutated inputs must be rejected
-- Each example builds a `bad : KeylessInput` by record-update of `Happy.input`
-- and asserts `keyless bad = none`.
-- ---------------------------------------------------------------------------

/-- Tampered RSA signature (every limb doubled, mod p) → RSA verify fails. -/
example :
  let bad : KeylessInput := { Happy.input with
    rsa := { Happy.input.rsa with
      signature := Happy.input.rsa.signature.map (· * 2) } }
  keyless bad = none := by native_decide

/-- Wrong `publicInputsHash` (set to 0) → final Poseidon-14 equality fails.
    Slowest negative test: runs the entire pipeline first. -/
example :
  let bad : KeylessInput := { Happy.input with publicInputsHash := 0 }
  keyless bad = none := by native_decide

/-- `request_with_incorrect_nonce` analog: tampered `epkBlinder` (42 → 0)
    causes `verifyNonce`'s Poseidon commitment to differ from the parsed
    `nonce.value`, so the equality assertion rejects. -/
example :
  let bad : KeylessInput := { Happy.input with
    commit := { Happy.input.commit with epkBlinder := 0 } }
  keyless bad = none := by native_decide

/-- `prove_request_with_invalid_epk_exp_date` analog: set `expDate` past
    `iat + expHorizon`. The circuit's `verifyTimestamp` runs
    `lessThan 64 expDate (iat + expHorizon)`; with the relation reversed it
    rejects. The `iat` value in the JWT is `1719866138`; the original
    `expHorizon` is `999999999999`, so we set `expDate := 2 * 10^12` (well
    above `iat + expHorizon ≈ 1.001 * 10^12`).
    Also requires bumping `publicInputsHash` because the new `expDate`
    feeds into the Poseidon-14 input — but the timestamp check fails first
    so any value of `publicInputsHash` reproduces the rejection. -/
example :
  let bad : KeylessInput := { Happy.input with
    commit := { Happy.input.commit with expDate := 2_000_000_000_000 } }
  keyless bad = none := by native_decide

/-- `prove_request_with_wrong_uid_key` analog: replace `uid.name` with a
    different ASCII triple (`"sun"` instead of `"sub"`). The
    `parseJWTFieldWithQuotedValue` parser checks every name byte against
    the JSON field-name region; mismatch rejects. -/
example :
  let badName : FString bn254 MAX_UID_NAME_LEN :=
    let bytes : Array Nat := #[115, 117, 110]  -- "sun"
    let padded := bytes ++ Array.replicate (MAX_UID_NAME_LEN - bytes.size) 0
    ⟨⟨padded.map mkChar, (Array.size_map ..).trans (by native_decide)⟩, 3⟩
  let bad : KeylessInput := { Happy.input with
    uid := { Happy.input.uid with name := badName } }
  keyless bad = none := by native_decide

end TestKeyless
