import Clap.Keyless

/-!
# Hand-written helpers for the generated `KeylessTestFixture`

The fixture file `Clap/Test/KeylessFixture.lean` is regenerated by
`scripts/input_json_to_lean.py`. To keep that file purely data, we put the
small reusable helpers here so they survive regeneration.
-/

namespace KeylessTestFixture
open Clap.Lang Core Primes ZMod Keyless HashToField

/-- Convert a Nat byte (0–255) to an `F8 bn254` (8-bit LSB-first field vector).
    Used to lift each character of every `FString` fixture from raw `Array Nat`. -/
def mkChar (n : Nat) : F8 bn254 := Clap.nat2bitsLsb 8 n

/-- Convert a Nat (for indices, single-bit `FB`, RSA limbs) to `F bn254`.
    Goes through `ZMod` because under the scoped `Clap.Lang.ZMod.instCoreZMod`,
    `F bn254 = ZMod bn254` definitionally. -/
def mkFB (n : Nat) : FB bn254 := (n : ZMod bn254)

/-- Mirror of `verifyPublicInputsHash` (Clap/Keyless.lean) without the final
    equality assertion: returns the *expected* `public_inputs_hash` Poseidon
    output for a given `KeylessInput`. Variant fixtures (e.g. AudOverride)
    use this to derive their hash field instead of relying on
    `circuit/tools/input_gen.py`'s hard-coded value, which has been observed
    stale. -/
def computePublicInputsHash (input : KeylessInput) : Option (F bn254) := do
  let performAudChecks : FB bn254 := FB.not input.audOverride.skipAudChecks
  let idc ← computeIdentityCommitment
    input.commit.pepper
    input.audOverride.privateAudValue
    performAudChecks
    input.uid.value
    input.uid.name
  let hashedIss ← hashBytesToFieldWithLen input.iss.value.toVF input.iss.value.len
  let hashedExtra ← hashBytesToFieldWithLen input.extra.extraField.toVF input.extra.extraField.len
  let hashedHeader ← hashBytesToFieldWithLen input.jwtRaw.b64u_jwt_header_w_dot.toVF
                     input.jwtRaw.b64u_jwt_header_w_dot.len
  let hashedPubkey ← hash64BitLimbsToFieldWithLen input.rsa.pubkeyModulus 64 RSA_KEY_BYTES
  let overrideHashed ← hashBytesToFieldWithLen input.audOverride.overrideAudValue.toVF
                       input.audOverride.overrideAudValue.len
  Clap.Poseidon.poseidonBN254
    [ input.commit.epk[0], input.commit.epk[1], input.commit.epk[2], input.commit.epkLen
    , idc
    , input.commit.expDate, input.commit.expHorizon
    , hashedIss, input.extra.useExtraField, hashedExtra
    , hashedHeader, hashedPubkey, overrideHashed
    , input.audOverride.useAudOverride
    ]

end KeylessTestFixture
