import Clap.Keyless

/-!
# Hand-written helpers for the generated `KeylessTestFixture`

The fixture file `Clap/Test/KeylessFixture.lean` is regenerated by
`scripts/input_json_to_lean.py`. To keep that file purely data, we put the
small reusable helpers here so they survive regeneration.
-/

namespace KeylessTestFixture
open Clap.Lang Primes Keyless HashToField

/-- Convert a Nat byte (0–255) to an `F bn254` field element.
    Used to lift each character of every `FString` fixture from raw `Array Nat`.
    Since the `FChar`/`F8` → `F` migration, `FString.data : Vector (F bn254)`,
    so each character is a single field element equal to its byte value. -/
def mkChar (n : Nat) : F bn254 := (n : ZMod bn254)

/-- Convert a Nat (for indices, single-bit `FB`, RSA limbs) to `F bn254`.
    Goes through `ZMod` since `F bn254` is just the abbrev `ZMod bn254`
    (see `Clap.Lang`). -/
def mkFB (n : Nat) : FB bn254 := (n : ZMod bn254)

/-- Mirror of `verifyPublicInputsHash` (Clap/Keyless.lean) without the final
    equality assertion: returns the *expected* `public_inputs_hash` Poseidon
    output for a given `KeylessInput`. Variant fixtures (e.g. AudOverride)
    use this to derive their hash field instead of relying on
    `circuit/tools/input_gen.py`'s hard-coded value, which has been observed
    stale. -/
def computePublicInputsHash (input : KeylessInput) : Option (F bn254) := do
  let performAudChecks : FB bn254 := FB.not input.audOverride.skipAudChecks
  let idc ← computeIdentityCommitment
    input.commit.pepper
    input.audOverride.privateAudValue
    performAudChecks
    input.uid.value
    input.uid.name
  -- Mirrors Keyless.verifyPublicInputsHash exactly (FStrings carry their own
  -- `.len`, so hashBytesToField takes them directly; pubkey uses the 64-bit-limb hash).
  let hashedIssValue ← hashBytesToField input.iss.value
  let hashedExtraField ← hashBytesToField input.extra.extraField
  let hashedJwtHeader ← hashBytesToField input.jwtRaw.b64u_jwt_header_w_dot
  let hashedPubkeyModulus ← hash64BitLimbsToField {data := input.rsa.pubkeyModulus, len := RSA_KEY_BYTES}
  let overrideAudValHashed ← hashBytesToField input.audOverride.overrideAudValue
  Clap.Poseidon.poseidonBN254
    #v[ input.commit.epk[0], input.commit.epk[1], input.commit.epk[2], input.commit.epkLen
    , idc
    , input.commit.expDate
    , input.commit.expHorizon
    , hashedIssValue
    , input.extra.useExtraField
    , hashedExtraField
    , hashedJwtHeader
    , hashedPubkeyModulus
    , overrideAudValHashed
    , input.audOverride.useAudOverride
    ]

end KeylessTestFixture
